-- Fill HEROES TABLE WITH JUSTICE LEAGUE HEROES
INSERT INTO HEROES (NAME) VALUES ('Batman');
INSERT INTO HEROES (NAME) VALUES ('Superman');
INSERT INTO HEROES (NAME) VALUES ('Flash');
INSERT INTO HEROES (NAME) VALUES ('Wonder Woman');
INSERT INTO HEROES (NAME) VALUES ('Cyborg');
